# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CentroidExtractor
                                 A QGIS plugin
 This plugin extracts centroids from polygons.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-10-28
        copyright            : (C) 2020 by George Thomas Muteti
        email                : thomas.muteti@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CentroidExtractor class from file CentroidExtractor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .centroid_extractor import CentroidExtractor
    return CentroidExtractor(iface)
